 SET(SDL2TTF_SEARCH_PATHS
  $ENV{PROGRAMFILES}/SDL2# WINDOWS
  "$ENV{PROGRAMFILES(X86)}/SDL2"# WINDOWS
  ~/Library/Frameworks
  /Library/Frameworks
  /usr/local
  /usr
  /sw # Fink
  /opt/local # DarwinPorts
  /opt/csw # Blastwave
  /opt
)

FIND_PATH(SDL2TTF_INCLUDE_DIR SDL_ttf.h
  HINTS
  $ENV{SDL2DIR}
  PATH_SUFFIXES include/SDL2 include
  PATHS ${SDL2TTF_SEARCH_PATHS}
)

FIND_LIBRARY(SDL2TTF_LIBRARY
  NAMES SDL2_ttf
  HINTS
  $ENV{SDL2DIR}
  PATH_SUFFIXES lib64 lib
  PATHS ${SDL2TTF_SEARCH_PATHS}
  DOC "SDL2 ttf Library Path"
)

INCLUDE(FindPackageHandleStandardArgs)

#message(${SDL2TTF_LIBRARY})

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2_ttf REQUIRED_VARS SDL2TTF_LIBRARY SDL2TTF_INCLUDE_DIR)

SET(SDL2TTF_FOUND "NO")
IF(SDL2TTF_LIBRARY AND SDL2TTF_INCLUDE_DIR)
  SET(SDL2TTF_FOUND "YES")
  MESSAGE(STATUS "Looking for SDL2_ttf - found")
ENDIF(SDL2TTF_LIBRARY AND SDL2TTF_INCLUDE_DIR)
